### ISSUE TITLE
Does WebRL support Mobile?

### ISSUE THREAD

**Issue by mrFranklin** [THUDM/WebRL#10]
Hi, I saw in your other paper that AutoGLM uses WebRL for training models. AutoGLM supports both web and mobile environments. Does WebRL already support training models in mobile environments? Or does AutoGLM use WebRL only for web environments and AndroidLab’s SFT models for mobile environments?

Sorry to ask here because AutoGLM is not open source yet.
Looking forward to your response. Thank you very much!

**Comment by Xiao9905** [comment]
@mrFranklin Thanks for your interest in WebRL. WebRL, theoretically, is an algorithm applicable for any LLM/LMM-based agent tasks. This repo is an application in the WebArena environment. If you are interested in applying WebRL in Android, you may select a proper environment and do the implementation.

**Comment by mrFranklin** [comment]
> @mrFranklin Thanks for your interest in WebRL. WebRL, theoretically, is an algorithm applicable for any LLM/LMM-based agent tasks. This repo is an application in the WebArena environment. If you are interested in applying WebRL in Android, you may select a proper environment and do the implementation.

Thanks. 
The android environment of AutoGLM is not use WebRL?  Do I understand it correctly?

**Comment by Xiao9905** [comment]
Both Phone Use and Web Browser Use of AutoGLM is developed based on WebRL algorithm.
