### ISSUE TITLE
请问这几个数据集在哪里可以找到和网站交互

### ISSUE THREAD

**Issue by wangjinghan666** [THUDM/WebRL#11]
![Screenshot_2024-11-28-13-20-43-184_com android browser](https://github.com/user-attachments/assets/f2a2c880-a753-4778-bbc1-2b6e9af1bbb9)
请问要进行sft训练的话需要LLaMA-Factory/data/dataset_info.json里面提到的数据集，但是我在这里只找到了web_policy_sft和几个其他的数据集，没有看到像web_orm这个，请问是应该把dataset_info.json里面的其他的数据集删掉再运行么，另外我还有一个问题就是，我们的代理是如何和web进行交换的呢，我在这里没有找到像是playwright或是其他工具相关的代码

**Comment by QZH-777** [comment]
Sorry, web_orm dataset is not released. We will release the trained ORM later. 
For interaction, please refer to the `interaction and evaluation` section of README.

**Comment by wangjinghan666** [comment]
> Sorry, web_orm dataset is not released. We will release the trained ORM later. For interaction, please refer to the `interaction and evaluation` section of README.

那我们用这里现有的文件还能进行sft训练么，没有orm的数据是不是以为着我们不能训练critic lm了

**Comment by 3201266226** [comment]
请问有提供orm的训练数据吗
