### ISSUE TITLE
Training WebRL error

### ISSUE THREAD

**Issue by CarlHuangNuc** [THUDM/WebRL#15]
![image](https://github.com/user-attachments/assets/24a8d723-ae54-4fa5-8a1e-764feecc71aa)
Hi Authors,

 I started training with the results of SFT. Do you know this error come from ?

**Comment by CarlHuangNuc** [comment]
found the reason ,thanks,

**Comment by lzy37ld** [comment]
@CarlHuangNuc Sorry, could u pls report a bit about how you resolve that?
