### ISSUE TITLE
Templated/incomplete `dataset_info.json` paths

### ISSUE THREAD

**Issue by matbee-eth** [THUDM/WebRL#2]
The following paths aren't available which causes a failure; namely `web_policy_sft_test`
```
  "web_policy_sft_test": {
    "file_name": "path_to_validation_data",
    "formatting": "sharegpt",
    "columns": {
        "messages": "conversations"
    }
  },
  "web_orm": {
    "file_name": "path_to_data_to_train_orm",
    "formatting": "sharegpt",
    "columns": {
      "messages": "conversations",
      "system": "system"
    }
  },
  "web_orm_test": {
    "file_name": "path_to_validation_data",
    "formatting": "sharegpt",
    "columns": {
      "messages": "conversations",
      "system": "system"
    }
  },
```

**Comment by matbee-eth** [comment]
I put some splits on HF: [matbee/web_policy_sft](https://huggingface.co/datasets/matbee/web_policy_sft)

**Comment by K-THU** [comment]
19 / 2000
I also encountered this problem. Did you solve it?

**Comment by K-THU** [comment]
I also encountered this problem. Did you solve it?

> The following paths aren't available which causes a failure; namely `web_policy_sft_test`
> 
> ```
>   "web_policy_sft_test": {
>     "file_name": "path_to_validation_data",
>     "formatting": "sharegpt",
>     "columns": {
>         "messages": "conversations"
>     }
>   },
>   "web_orm": {
>     "file_name": "path_to_data_to_train_orm",
>     "formatting": "sharegpt",
>     "columns": {
>       "messages": "conversations",
>       "system": "system"
>     }
>   },
>   "web_orm_test": {
>     "file_name": "path_to_validation_data",
>     "formatting": "sharegpt",
>     "columns": {
>       "messages": "conversations",
>       "system": "system"
>     }
>   },
> ```



I also encountered this problem. Did you solve it?

**Comment by matbee-eth** [comment]
I did.
```
huggingface-cli download --repo-type dataset matbee/web_policy_sft --local-dir LLaMa-Factory/data/
```

Update the `web_policy_sft` JSON entries in `LLaMa-Factory/data/`
```
  "web_policy_sft": {
    "file_name": "web_policy_sft_train.json",
    "formatting": "sharegpt",
    "columns": {
        "messages": "conversations"
    }
  },
  "web_policy_sft_test": {
    "file_name": "web_policy_sft_eval.json",
    "formatting": "sharegpt",
    "columns": {
        "messages": "conversations"
    }
  },
```

**Comment by six-finger** [comment]
Thanks a lot! 
But how did you find the data?

**Comment by matbee-eth** [comment]
the data is in the repo, its just not split and in one large json
