### ISSUE TITLE
What's the input of the ORM?

### ISSUE THREAD

**Issue by Fu-Dayuan** [THUDM/WebRL#22]
eg 这个action带element吗？最后一个html是指生成最后一个action的html还是执行完最后一个action之后的？

**Comment by Fu-Dayuan** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/95cc8e32-0c92-45d3-8aef-365631c796b0">
以及这个perplexity计算是按找步骤来还是按照instance来？（也就是说计算一个问题所有步的perplexity 还是计算一个单独步骤的？后者会导致只有一部分步骤在训练数据中）

**Comment by Fu-Dayuan** [comment]
以及能提供webrl训练格式吗（包括原版&加buffer的）。由于webarena-lite可能被你们改过，你们提供的代码有点问题（trace文件夹里就没有jsonl文件）

**Comment by QZH-777** [comment]
> eg 这个action带element吗？最后一个html是指生成最后一个action的html还是执行完最后一个action之后的？

<img width="828" alt="image" src="https://github.com/user-attachments/assets/2e171597-1631-4588-8807-a9ea4adba529" />

prompt = f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{user_prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

**Comment by QZH-777** [comment]
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/77482343/394379650-95cc8e32-0c92-45d3-8aef-365631c796b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzg4NTAsIm5iZiI6MTczNDMzODU1MCwicGF0aCI6Ii83NzQ4MjM0My8zOTQzNzk2NTAtOTVjYzhlMzItMGM5Mi00NWQzLThhZWYtMzY1NjMxYzc5NmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWEwM2Y0MDA1MDQ0ZGI1OTlkNzhkMDRjMzk0YzM0YjMzN2VkNTU3NjAwMjAzOWRmM2QyYzE0NDk1NGU5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eEjbWAbojlC3S5lHVaJ2Klllgd-MwKwfl8fcRlvw6W0"> 以及这个perplexity计算是按找步骤来还是按照instance来？（也就是说计算一个问题所有步的perplexity 还是计算一个单独步骤的？后者会导致只有一部分步骤在训练数据中）

Calculate the ppl of a single step

**Comment by QZH-777** [comment]
> 以及能提供webrl训练格式吗（包括原版&加buffer的）。由于webarena-lite可能被你们改过，你们提供的代码可能搞不出来最终结果（trace文件夹里就没有jsonl文件）

Please execute the interaction script we provided in [VAB](https://github.com/THUDM/VisualAgentBench/tree/main/VAB-WebArena-Lite#-evaluating-in-webrl-setting-text-modal) to get the corresponding trace file
