### ISSUE TITLE
mismatched context length

### ISSUE THREAD

**Issue by cyh2004** [THUDM/WebRL#23]
Hello, I've noticed that the base model 'glm-4-9b' released in huggingface has a context length of 8192
But the context length of 'webrl-glm-4-9b' is 16384
'webrl-glm-4-9b' should have been finetuned from 'glm-4-9b'. Why is the context length doubled?

**Comment by K-THU** [comment]
I also encountered the same problem.

**Comment by QZH-777** [comment]
During training, we modify the "seq_length" in the config.json file of glm-4-9b to 16384,
