### ISSUE TITLE
How to get the configuration file after sft

### ISSUE THREAD

**Issue by lzy37ld** [THUDM/WebRL#24]
Hi, thanks for your great job. I am trying to play around with your code but met some issues.

If I understand correctly, I have to configure a file like `test_webarena_lite.raw.json` for the corresponding instruction from `webrl-sft-data`. However, I have no idea about the supposed configuration file for each task instruction from `webrl-sft-data`, for example the site and start-url. Could u pls give some help here? Appreciate!

**Comment by lzy37ld** [comment]
Besides, I guess we need the reward function from VAB-lite given the line 3 of algorithm 1 in the paper. Could u help with this as well? Thanks!

**Comment by lzy37ld** [comment]
Hi, could you please help with this issue?

**Comment by QZH-777** [comment]
> Hi, could you please help with this issue?

You can use the reward model we provide to evaluate the correctness of the rollouts. Specifically, you can  configure each task in the following format:
```
{
  
  "sites": [
    <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
  ],
  "task_id": <Your task id>
  "require_login": true,
  "storage_state": "./.auth/shopping_admin_state.json",
  "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
  "geolocation": null,
  "intent_template": "",
  "instantiation_dict": {},
  "intent": <Task>,
  "require_reset": false,
  "eval": {
    "eval_types": [
      "string_match"
    ],
    "reference_answers": {
      "exact_match": "N/A"
    },
    "reference_url": "",
    "program_html": [],
    "string_note": "",
    "reference_answer_raw_annotation": ""
  },
  "intent_template_id": 0
}
```

You need to modify the `sites`, `task_id`, `start_url` and `intent` based on the task. After completing the configuration, you can perform interaction and use ORM to label the trajectory.

**Comment by lzy37ld** [comment]
Yeah, I get your point.
I guess my question is: How to get the config file (i.e. the `sites`, `task_id`, `start_url`) based on the sft data at [here](https://raw.githubusercontent.com/THUDM/WebRL/refs/heads/main/LLaMA-Factory/data/web_policy_sft.json). Is there any metadata about the SFT data so that I could configure each tasks?

**Comment by QZH-777** [comment]
I understand your problem. I provide [WebArena-Lite_info.json](https://github.com/THUDM/WebRL/blob/main/WebArena-Lite_info.json), which contains all the tasks in the SFT data along with the corresponding `sites` and `start_url`. Regarding `task_id`, you can set it as you like, just make sure it varies from task to task.
