### ISSUE TITLE
大概需要多少资源才能训出来？

### ISSUE THREAD

**Issue by Fu-Dayuan** [THUDM/WebRL#26]
to 作者:
下面的讨论和这个问题没关系，这个问题还是没解决

rt 单机8卡A100 存储 1.8T cpu 96核 bs_per_device=1 在critic forward的时候就爆GPU OOM了(deepspeed给cpu分了600G左右的配额)

有多机训练也一样会oom爆掉

**Comment by Fu-Dayuan** [comment]
参数仅改动：

**Comment by lzy37ld** [comment]
hi, 请问一下，你的webrl 的training dataset是什么？ 如果我理解没错，应该是他们的sft training的数据，但是那些数据，没有Webarena的configuration？

**Comment by Fu-Dayuan** [comment]
> hi, 请问一下，你的webrl 的training dataset是什么？ 如果我理解没错，应该是他们的sft training的数据，但是那些数据，没有Webarena的configuration？

跑完了拿orm打了一下，没管webarena-liite reward

**Comment by Fu-Dayuan** [comment]
> hi, 请问一下，你的webrl 的training dataset是什么？ 如果我理解没错，应该是他们的sft training的数据，但是那些数据，没有Webarena的configuration？

网站啥的默认只有一个，然后拿初始网页匹配的

**Comment by lzy37ld** [comment]
我有点没太get到。
就是我目前理解是：
每个intent要有一个对应的如下的config：
```python
{
  "sites": [
    <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
  ],
  "task_id": <Your task id>
  "require_login": true,
  "storage_state": "./.auth/shopping_admin_state.json",
  "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
  "geolocation": null,
  "intent_template": "",
  "instantiation_dict": {},
  "intent": <Task>,
  "require_reset": false,
  "eval": {
    "eval_types": [
      "string_match"
    ],
    "reference_answers": {
      "exact_match": "N/A"
    },
    "reference_url": "",
    "program_html": [],
    "string_note": "",
    "reference_answer_raw_annotation": ""
  },
  "intent_template_id": 0
}
```
但是我只在sft那里看到了他们training datasets的intent，并没有看到config，比如sites或者start_url之类的。

我感觉我上述说的这个步骤是为了执行，step 2 in the [algorithm 1](https://arxiv.org/pdf/2411.02337#page=17.10).

**Comment by Fu-Dayuan** [comment]
> 我有点没太get到。 就是我目前理解是： 每个intent要有一个对应的如下的config：
> 
> ```python
> {
>   "sites": [
>     <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
>   ],
>   "task_id": <Your task id>
>   "require_login": true,
>   "storage_state": "./.auth/shopping_admin_state.json",
>   "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
>   "geolocation": null,
>   "intent_template": "",
>   "instantiation_dict": {},
>   "intent": <Task>,
>   "require_reset": false,
>   "eval": {
>     "eval_types": [
>       "string_match"
>     ],
>     "reference_answers": {
>       "exact_match": "N/A"
>     },
>     "reference_url": "",
>     "program_html": [],
>     "string_note": "",
>     "reference_answer_raw_annotation": ""
>   },
>   "intent_template_id": 0
> }
> ```
> 
> 但是我只在sft那里看到了他们training datasets的intent，并没有看到config，比如sites或者start_url之类的。
> 
> 我感觉我上述说的这个步骤是为了执行，step 2 in the [algorithm 1](https://arxiv.org/pdf/2411.02337#page=17.10).

拿sft数据的网站匹配找到每个占位符该填什么

**Comment by lzy37ld** [comment]
> > 我有点没太get到。 就是我目前理解是： 每个intent要有一个对应的如下的config：
> > ```python
> > {
> >   "sites": [
> >     <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
> >   ],
> >   "task_id": <Your task id>
> >   "require_login": true,
> >   "storage_state": "./.auth/shopping_admin_state.json",
> >   "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
> >   "geolocation": null,
> >   "intent_template": "",
> >   "instantiation_dict": {},
> >   "intent": <Task>,
> >   "require_reset": false,
> >   "eval": {
> >     "eval_types": [
> >       "string_match"
> >     ],
> >     "reference_answers": {
> >       "exact_match": "N/A"
> >     },
> >     "reference_url": "",
> >     "program_html": [],
> >     "string_note": "",
> >     "reference_answer_raw_annotation": ""
> >   },
> >   "intent_template_id": 0
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是我只在sft那里看到了他们training datasets的intent，并没有看到config，比如sites或者start_url之类的。
> > 我感觉我上述说的这个步骤是为了执行，step 2 in the [algorithm 1](https://arxiv.org/pdf/2411.02337#page=17.10).
> 
> 拿sft数据的网站匹配找到每个占位符该填什么，然后自己构建这个就行，反正你也是拿orm打分，最后的分不关键，所以不需要管参考答案

对，明白你意思，就是`sft数据的网站`这个哪里有提供吗？我目前没有找到任何相关的数据。
这个codebase里面的`web_policy_sft.json`里面只有处理过后的数据，没有metadata之类的东西

**Comment by lzy37ld** [comment]
> > > > 我有点没太get到。 就是我目前理解是： 每个intent要有一个对应的如下的config：
> > > > ```python
> > > > {
> > > >   "sites": [
> > > >     <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
> > > >   ],
> > > >   "task_id": <Your task id>
> > > >   "require_login": true,
> > > >   "storage_state": "./.auth/shopping_admin_state.json",
> > > >   "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
> > > >   "geolocation": null,
> > > >   "intent_template": "",
> > > >   "instantiation_dict": {},
> > > >   "intent": <Task>,
> > > >   "require_reset": false,
> > > >   "eval": {
> > > >     "eval_types": [
> > > >       "string_match"
> > > >     ],
> > > >     "reference_answers": {
> > > >       "exact_match": "N/A"
> > > >     },
> > > >     "reference_url": "",
> > > >     "program_html": [],
> > > >     "string_note": "",
> > > >     "reference_answer_raw_annotation": ""
> > > >   },
> > > >   "intent_template_id": 0
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 但是我只在sft那里看到了他们training datasets的intent，并没有看到config，比如sites或者start_url之类的。
> > > > 我感觉我上述说的这个步骤是为了执行，step 2 in the [algorithm 1](https://arxiv.org/pdf/2411.02337#page=17.10).
> > > 
> > > 
> > > 拿sft数据的网站匹配找到每个占位符该填什么，然后自己构建这个就行，反正你也是拿orm打分，最后的分不关键，所以不需要管参考答案
> > 
> > 
> > 对，明白你意思，就是`sft数据的网站`这个哪里有提供吗？我目前没有找到任何相关的数据。 这个codebase里面的`web_policy_sft.json`里面只有处理过后的数据，没有metadata之类的东西
> 
> 输入里面有HTML......如果这个HTML里面有openstreetmap，那显然就是map任务。其他的同理

hh,懂你意思了，一个个看html确实是一个办法,但是考虑里面有9460个examples, 我感觉author是不是放出来这个会好一点

**Comment by Fu-Dayuan** [comment]
> > > > > 我有点没太get到。 就是我目前理解是： 每个intent要有一个对应的如下的config：
> > > > > ```python
> > > > > {
> > > > >   "sites": [
> > > > >     <site> # possible choices: "shopping_admin", "map", "shopping", "reddit", "gitlab"
> > > > >   ],
> > > > >   "task_id": <Your task id>
> > > > >   "require_login": true,
> > > > >   "storage_state": "./.auth/shopping_admin_state.json",
> > > > >   "start_url": <start url of site>, # possible choices: "__SHOPPING_ADMIN__", "__SHOPPING__", "__GITLAB__", "__MAP__", "__REDDIT__"
> > > > >   "geolocation": null,
> > > > >   "intent_template": "",
> > > > >   "instantiation_dict": {},
> > > > >   "intent": <Task>,
> > > > >   "require_reset": false,
> > > > >   "eval": {
> > > > >     "eval_types": [
> > > > >       "string_match"
> > > > >     ],
> > > > >     "reference_answers": {
> > > > >       "exact_match": "N/A"
> > > > >     },
> > > > >     "reference_url": "",
> > > > >     "program_html": [],
> > > > >     "string_note": "",
> > > > >     "reference_answer_raw_annotation": ""
> > > > >   },
> > > > >   "intent_template_id": 0
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 但是我只在sft那里看到了他们training datasets的intent，并没有看到config，比如sites或者start_url之类的。
> > > > > 我感觉我上述说的这个步骤是为了执行，step 2 in the [algorithm 1](https://arxiv.org/pdf/2411.02337#page=17.10).
> > > > 
> > > > 
> > > > 拿sft数据的网站匹配找到每个占位符该填什么，然后自己构建这个就行，反正你也是拿orm打分，最后的分不关键，所以不需要管参考答案
> > > 
> > > 
> > > 对，明白你意思，就是`sft数据的网站`这个哪里有提供吗？我目前没有找到任何相关的数据。 这个codebase里面的`web_policy_sft.json`里面只有处理过后的数据，没有metadata之类的东西
> > 
> > 
> > 输入里面有HTML......如果这个HTML里面有openstreetmap，那显然就是map任务。其他的同理
> 
> hh,懂你意思了，一个个看html确实是一个办法,但是考虑里面有9460个examples, 我感觉author是不是放出来这个会好一点

你把task merge之后只有1000多个，写个脚本也就1h，几个unique的关键词匹配就能搞定了

**Comment by Fu-Dayuan** [comment]
猜出原因了，solved

不过我建议作者把webrl.yaml里的batch size改个名（至少在哪里加个per_device）

要不很容易让人理解成这是总batchsize（也就是128）然后可以根据per参数/累计参数就可以通过batchsize反着算回去每个卡的batchsize，因为一般脚本逻辑都是这样
