### ISSUE TITLE
当我在第0阶段之后，进入第一阶段生成数据之前，我得到的交互后的数据，我该运行哪个脚本？

### ISSUE THREAD

**Issue by K-THU** [THUDM/WebRL#27]
当我在第0阶段之后，进入第一阶段生成数据之前，我得到的交互后的数据，我该运行哪个脚本？是先python scripts/gen_task.py这个脚本还是你们后来发布的scripts/process_data.py这个脚本？

**Comment by lzy37ld** [comment]
hi,请问你是如何获得每个training example所对应的config file的呢？

https://github.com/THUDM/WebRL/issues/24

**Comment by K-THU** [comment]
> hi,请问你是如何获得每个training example所对应的config file的呢？
> 
> Detail in : #24

自己改写的，在另外一个仓库VAB中有一个脚本generate_test_data.py 
链接是https://github.com/THUDM/VisualAgentBench/tree/main/VAB-WebArena-Lite#-evaluating-in-webrl-setting-text-modal

**Comment by QZH-777** [comment]
> 当我在第0阶段之后，进入第一阶段生成数据之前，我得到的交互后的数据，我该运行哪个脚本？是先python scripts/gen_task.py这个脚本还是你们后来发布的scripts/process_data.py这个脚本？

在得到WebArena-Lite的交互数据后，需要先执行gen_task.py得到新任务，然后对新任务进行rollout，对rollout的结果执行process_data.py

**Comment by K-THU** [comment]
可否详细说明一下进入第0阶段后gen_task.py中第43行critic_lm和第44行指定critic_resume的参数吗，也就是用critic的模型对新任务指令进行打分和筛选，这里的critic模型是指定的orm吗？
