### ISSUE TITLE
在script/gen_task.py的生成数据脚本的第72行path = "path of file that contains failed instructions"，关于这个失败任务指令的文件json，里面数据格式是怎么样的

### ISSUE THREAD

**Issue by K-THU** [THUDM/WebRL#28]
在script/gen_task.py的生成数据脚本的第72行path = "path of file that contains failed instructions"，关于这个失败任务指令的文件json，里面数据格式是怎么样的

**Comment by QZH-777** [comment]
每个样本的格式为{"web": "", "task": ""}
其中web的范围是[shopping_admin, shopping, map, reddit, gitlab]
