### ISSUE TITLE
Question about Inference 

### ISSUE THREAD

**Issue by minkyudalpha** [THUDM/WebRL#3]
Hello, "It was a very interesting paper.!

How can I inference those checkpoint? 

Can I use it at Visual Bench Light?

Or Is there any plan for inference scripts?

**Comment by QZH-777** [comment]
Thank you for raising this issue! We will release the inference scripts in this week!

**Comment by korbinian-hoermann** [comment]
Hi @QZH-777 

Was the inference script already released somewhere ? I could not find it

**Comment by korbinian-hoermann** [comment]
Hi @QZH-777 , 

This section says: 

"For details on environment deployment and interaction code, please refer to [interaction](https://github.com/THUDM/WebRL/blob/main/interaction)."

But the link gives me a: 
404 - page not found

**Comment by QZH-777** [comment]
> Hi @QZH-777 ,
> 
> This section says:
> 
> "For details on environment deployment and interaction code, please refer to [interaction](https://github.com/THUDM/WebRL/blob/main/interaction)."
> 
> But the link gives me a: 404 - page not found

Apologies for the issue; we have now resolved this problem in README.
