### ISSUE TITLE
About the tranning process for ORM

### ISSUE THREAD

**Issue by K-THU** [THUDM/WebRL#30]
Would you  open source the training code and algorithm process for ORM? I saw the training parameters for ORM in the paper. The algorithm training process mentioned in the paper seems to only include the training parameters and process for the actor-critic, but there seems to be no algorithm process for ORM. Although the ORM model has been open-sourced, it seems that different web data might require different ORM?

**Comment by QZH-777** [comment]
Sorry, we are only planning to open source the trained ORM, the training data is not going to be open source. The training code is just using the SFT training script in llama-factory.
