### ISSUE TITLE
关于gen_task.py中的filter_by_critic

### ISSUE THREAD

**Issue by K-THU** [THUDM/WebRL#31]
可否详细说明一下进入第0阶段后gen_task.py中第43行critic_lm和第44行指定critic_resume的参数吗，也就是用critic的模型对新任务指令进行打分和筛选，这里的critic模型是指定的orm吗？

**Comment by QZH-777** [comment]
在刚执行完SFT之后，我们还没有critic，所以这时候并不需要使用critic进行筛选。
在之后的每一轮RL训练中，我们会得到actor和critic，这时候就可以使用critic进行筛选。
当然，也可以用ORM来进行筛选，这时候就根据ORM输出YES的归一化概率P(YES) \ (P(YES)+P(NO))，作为筛选指标。
