### ISSUE TITLE
any more documents?

### ISSUE THREAD

**Issue by zhengshf** [THUDM/WebRL#6]
It can provide more detailed process description documents for SFT, PPO, and inference, including model configuration, data configuration, etc. for running through the preliminary process.

**Comment by QZH-777** [comment]
Here is a pseudocode for the training process.
<img width="706" alt="image" src="https://github.com/user-attachments/assets/d6c2f7b6-8590-4455-af53-6a250f8e8c5c">


Please refer to our paper for more details.

**Comment by zhengshf** [comment]
thks a lot !!!!
